databases:
  - name: handei-db
    databaseName: handei
    user: handei_user
    plan: free

services:
  - type: web
    name: handei-website
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://handei-website.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: handei-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: handei-db
          property: port  
      - key: DB_DATABASE
        fromDatabase:
          name: handei-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: handei-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: handei-db
          property: password
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: info@handeizimbabwe.com
      - key: MAIL_FROM_NAME
        value: "Handei Zimbabwe"
      - key: NEXT_PUBLIC_API_URL
        value: https://handei-website.onrender.com/api