databases:
  - name: handei-db
    databaseName: handei
    user: handei_user
    plan: starter
    region: oregon

services:
  # Main web service
  - type: web
    name: handei-website
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://handei-website.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: handei-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: handei-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: handei-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: handei-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: handei-db
          property: password
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: info@handeizimbabwe.com
      - key: MAIL_FROM_NAME
        value: Handei Zimbabwe
      - key: NEXT_PUBLIC_API_URL
        value: https://handei-website.onrender.com/api
    buildCommand: |
      # Build assets
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      /usr/local/bin/start.sh